(() => {
  const categoryMap = {
    'ЧТО ТАКОЕ 3115?':['О системе','⌁'], 'ГЛАВНЫЕ ПЕРСОНАЖИ':['Персонажи','♟'], 'МЕСТА СИЛЫ':['Места','⌂'], 'АРТЕФАКТЫ':['Артефакты','◈'], 'АРТЕФАКТЫ И ОРУЖИЕ ГУРИН ДЖИХАДА':['Артефакты','◈'], 'ПОНЯТИЯ И КРИКИ':['Словарь','⌘'], 'ВРАГИ И СОЮЗНИКИ':['Стороны конфликта','⚔'], 'КОНЕЦ ЛОРА':['Хроники','◷'], 'ЧАСТЬ 1: ПРЕДЫСТОРИЯ':['Хроники','◷'], 'ЧАСТЬ 2: ФИЛОСОФИЯ ПЫЩ-ПАРАДА':['Правила подвала','⌘'], 'ЧАСТЬ 3: ИСТОРИЯ ПЫЩ-ПАРАДА':['Хроники','◷'], 'ЧАСТЬ 4: СВЯЩЕННЫЕ МЕСТА':['Места','⌂'], 'ЧАСТЬ 5: ВОЙНЫ И БИТВЫ':['Хроники','◷'], 'ЧАСТЬ 5: ГУРИН ДЖИХАД (ДОКТРИНА, ОРУЖИЕ И ВЕЛИКИЕ БИТВЫ)':['Хроники','◷'], 'ЧАСТЬ 6: ЭКОНОМИКА ПЫЩ-ПАРАДА':['Экономика','₲'], 'ЧАСТЬ 7: РИТУАЛЫ И ТРАДИЦИИ':['Ритуалы','✳'], 'ЧАСТЬ 8: ПРОРОЧЕСТВА':['Пророчества','◇'], 'ЧАСТЬ 9: СИМВОЛЫ И ЗНАКИ':['Артефакты','◈'], 'ЧАСТЬ 10: КОНЕЦ И НАЧАЛО':['Хроники','◷']
  };
  const photoMap = {'ГУРЫЧ':'GURYCH.jpg','DJ ГУРЫЧ':'DJ_GURYCH.jpg','БРИТВЕНЬ':'BRITVEN.jpg','РАММ':'RAMM.jpg','ЗАВУЧ':'ZAVUCH.jpg','СИДОРОВ':'SIDOROV.jpg','ЕГОР':'EGOR.jpg','МАРК':'MARK.jpg','КОСТЮК':'KOSTYUK.jpg','МАКС':'MAX.jpg','ХМУРЫЧ':'KHMURYCH.jpg','БИГМУК':'BIGMUK.jpg','ЕПЫП':'YEPYP.jpg','ПЫХТЫЧ':'PYKHTYCH.jpg','СКЛИЗКИЙ ЖИЖ':'ZHIZH.jpg'};
  const icons = {'Персонажи':'♟','Места':'⌂','Артефакты':'◈','Словарь':'⌘','Стороны конфликта':'⚔','История и события':'◷','Правила подвала':'⌘','Сражения':'⚔','Экономика':'₲','Ритуалы':'✳','Пророчества':'◇','Финал':'∞','Хроники':'◷','О системе':'⌁'};
  const source = window.LORE_SOURCE || '';
  const lines = source.replace(/\r/g,'').split('\n');
  const groups = new Map(); let section = 'О системе'; let sectionIcon = '⌁'; let activeItem = null; let rootTitle = '';
  const flush = () => { if(activeItem){ const body=activeItem.lines.join('\n').trim(); if(body){const item={title:activeItem.title,body,section:activeItem.section,icon:activeItem.icon}; if(!groups.has(item.section))groups.set(item.section,[]); groups.get(item.section).push(item);} activeItem=null; } };
  for(const line of lines){
    if(/^# /.test(line)){flush();rootTitle=line.replace(/^# /,'').trim();continue;}
    if(/^## /.test(line)){flush();const heading=line.replace(/^## /,'').trim();const mapped=categoryMap[heading]||[heading,'⌁'];section=mapped[0];sectionIcon=mapped[1];activeItem={title:heading,lines:[],section,icon:sectionIcon};continue;}
    if(/^### /.test(line)){flush();activeItem={title:line.replace(/^### /,'').trim(),lines:[],section,icon:sectionIcon};continue;}
    if(activeItem)activeItem.lines.push(line);
  }
  flush();
  const nav=document.getElementById('category-nav'), grid=document.getElementById('card-grid'), filters=document.getElementById('filter-row'), search=document.getElementById('search');
  const categories=[...groups.keys()]; let current=categories.includes('Персонажи')?'Персонажи':categories[0];let currentFilter='Все';let query='';
  const allItems=[...groups.values()].flat();
  document.getElementById('entry-count').textContent=`${allItems.length} ЗАПИСЕЙ // ${categories.length} РАЗДЕЛОВ`;
  const titleFor=key=>key;
  function drawNav(){nav.innerHTML='';for(const name of categories){const btn=document.createElement('button');btn.className='nav-item'+(current===name?' active':'');btn.innerHTML=`<span class="nav-icon">${icons[name]||'⌁'}</span><span>${escapeHtml(name)}</span>`;btn.onclick=()=>selectCategory(name);nav.append(btn)}}
  function selectCategory(name){current=name;currentFilter='Все';drawNav();drawFilters();document.getElementById('section-title').textContent=titleFor(name).toLocaleUpperCase('ru');document.getElementById('sidebar').classList.remove('open');render()}
  function drawFilters(){filters.innerHTML='';const items=groups.get(current)||[];const types=['Все',...new Set(items.map(item=>item.section))];for(const type of types){const chip=document.createElement('button');chip.className='filter-chip'+(currentFilter===type?' active':'');chip.textContent=type;chip.onclick=()=>{currentFilter=type;drawFilters();render()};filters.append(chip)}}
  function inline(text){return escapeHtml(text).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`(.+?)`/g,'<strong>$1</strong>')}
  function bodyHtml(text){const rows=text.split('\n');let html='',list='',table=false;const closeList=()=>{if(list){html+=`</${list}>`;list=''}};const closeTable=()=>{if(table){html+='</tbody></table>';table=false}};for(const raw of rows){const line=raw.trim();if(!line){closeList();closeTable();continue}if(/^\|.*\|$/.test(line)){closeList();const cells=line.split('|').slice(1,-1).map(x=>x.trim());if(cells.every(x=>/^:?-{3,}:?$/.test(x)))continue;if(!table){html+='<table><tbody>';table=true}const isHeader=html.endsWith('<tbody>');html+=`<tr>${cells.map(cell=>`<${isHeader?'th':'td'}>${inline(cell.replace(/\*\*/g,''))}</${isHeader?'th':'td'}>`).join('')}</tr>`;continue}closeTable();if(/^####? /.test(line)){closeList();html+=`<h4>${inline(line.replace(/^####? /,''))}</h4>`;continue}if(/^[-*] /.test(line)||/^\d+\. /.test(line)){const ordered=/^\d+\. /.test(line),type=ordered?'ol':'ul';if(list!==type){closeList();list=type;html+=`<${list}>`}html+=`<li>${inline(line.replace(/^([-*] |\d+\. )/,''))}</li>`;continue}closeList();if(/^>/.test(line)){html+=`<blockquote>${inline(line.replace(/^>\s?/,''))}</blockquote>`}else{html+=`<p>${inline(line)}</p>`}}closeList();closeTable();return html}
  function imageFor(item){if(current!=='Персонажи')return '';const key=item.title.replace(/\s*\([^)]*\)/g,'').trim().toLocaleUpperCase('ru');const file=photoMap[key];return file?`<img src="${encodeURI(file)}" alt="Портрет: ${escapeHtml(item.title)}" loading="lazy" onerror="this.parentElement.innerHTML='<div class=&quot;no-photo&quot;><span>▧</span>ФОТОГРАФИИ<br>ПОКА НЕТ</div>'">`:`<div class="no-photo"><span>▧</span>ФОТОГРАФИИ<br>ПОКА НЕТ</div>`}
  function render(){if(window.ARCHIVE3115&&window.ARCHIVE3115.onRender)window.ARCHIVE3115.onRender(current);const items=(groups.get(current)||[]).filter(item=>(currentFilter==='Все'||item.section===currentFilter)&&(!query||`${item.title} ${item.body} ${item.section}`.toLocaleLowerCase('ru').includes(query)));grid.innerHTML='';for(let i=0;i<items.length;i++){const item=items[i],card=document.createElement('article');card.className='lore-card'+(item.body.length>570?' collapsed':'');const char=current==='Персонажи';const photo=imageFor(item);const subtitle=char?item.title.match(/\(([^)]+)\)/)?.[1]:'';card.innerHTML=`${char?`<div class="card-top"><div class="portrait">${photo}</div><div class="card-heading"><div class="card-index">PERSONA // ${(i+1).toString().padStart(2,'0')}</div><h3>${escapeHtml(item.title.replace(/\s*\([^)]*\)/g,'').trim())}</h3>${subtitle?`<p class="subtitle">${escapeHtml(subtitle)}</p>`:''}</div></div>`:`<div class="card-top"><div class="card-heading"><div class="card-index">${escapeHtml(item.section.toUpperCase())} // ${(i+1).toString().padStart(2,'0')}</div><h3>${escapeHtml(item.title)}</h3></div></div>`}<div class="card-body">${bodyHtml(item.body)}</div>${item.body.length>570?'<div class="card-actions"><button class="expand-btn">РАЗВЕРНУТЬ ↓</button></div>':''}`;const exp=card.querySelector('.expand-btn');if(exp)exp.onclick=()=>{const collapsed=card.classList.toggle('collapsed');exp.textContent=collapsed?'РАЗВЕРНУТЬ ↓':'СВЕРНУТЬ ↑'};grid.append(card)}document.getElementById('result-count').textContent=`${items.length} ${word(items.length,['ЗАПИСЬ','ЗАПИСИ','ЗАПИСЕЙ'])}`;document.getElementById('empty-state').hidden=items.length>0;grid.hidden=items.length===0}
  function word(n,forms){const k=n%10===1&&n%100!==11?0:n%10>=2&&n%10<=4&&!(n%100>=12&&n%100<=14)?1:2;return forms[k]}
  function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  drawNav();drawFilters();render();search.addEventListener('input',()=>{query=search.value.trim().toLocaleLowerCase('ru');render()});document.getElementById('menu-toggle').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==search){e.preventDefault();search.focus()}if(e.key==='Escape'){document.getElementById('sidebar').classList.remove('open');search.blur()}});
  const canvas=document.getElementById('smoke-canvas'),ctx=canvas.getContext('2d'),particles=[];let raf=0,density=0;const hud=document.getElementById('smoke-hud');function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();function puff(x,y,n=20){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=1+Math.random()*3;particles.push({x:x+(Math.random()-.5)*40,y:y+(Math.random()-.5)*35,vx:Math.cos(a)*s,vy:Math.sin(a)*s-1.5,r:30+Math.random()*35,alpha:.22+Math.random()*.22,decay:.002+Math.random()*.002,hue:115+Math.random()*35})}}function animate(){ctx.clearRect(0,0,innerWidth,innerHeight);for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx;p.y+=p.vy;p.r+=.7;p.alpha-=p.decay;if(p.alpha<=0){particles.splice(i,1);continue}const g=ctx.createRadialGradient(p.x,p.y,p.r*.08,p.x,p.y,p.r);g.addColorStop(0,`hsla(${p.hue},55%,30%,${p.alpha})`);g.addColorStop(.55,`hsla(${p.hue},35%,17%,${p.alpha*.55})`);g.addColorStop(1,`hsla(${p.hue},25%,8%,0)`);ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}density=Math.max(0,density-11);document.getElementById('smoke-density-val').textContent=`${Math.round(density)}%`;document.getElementById('smoke-status-text').textContent=density>180?'ЗАВУЧ В ДЫМУ НЕ ВИДИТ! ТУРБИНА НА МАКСИМУМЕ!':density>35?'ДЫМ РАССЕИВАЕТСЯ… ТРЕБУЕТСЯ ПЫЩ!':'АТМОСФЕРА СТАБИЛИЗИРОВАНА';if(particles.length){raf=requestAnimationFrame(animate)}else{raf=0;canvas.classList.remove('active');hud.classList.remove('visible')}}function pysh(){const points=[[innerWidth*.5,innerHeight*.92],[innerWidth*.2,innerHeight*.8],[innerWidth*.8,innerHeight*.83],[innerWidth*.5,innerHeight*.52],[innerWidth*.12,innerHeight*.3],[innerWidth*.9,innerHeight*.25]];points.forEach(([x,y])=>puff(x,y,23));density=3115;canvas.classList.add('active');hud.classList.add('visible');document.body.classList.remove('screen-shake');void document.body.offsetWidth;document.body.classList.add('screen-shake');setTimeout(()=>document.body.classList.remove('screen-shake'),500);if(!raf)animate();try{const C=window.AudioContext||window.webkitAudioContext;if(C){const a=new C(),o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.setValueAtTime(135,a.currentTime);o.frequency.exponentialRampToValueAtTime(38,a.currentTime+.45);g.gain.setValueAtTime(.17,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.6);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.6);o.onended=()=>a.close()}}catch(_){}}
  document.getElementById('pysh-button').addEventListener('click',pysh);
  window.ARCHIVE3115 = {
    groups,
    categories,
    icons,
    photoMap,
    allItems,
    get current(){ return current },
    get filter(){ return currentFilter },
    titleFor,
    escapeHtml,
    inline,
    bodyHtml,
    imageFor,
    word,
    selectCategory,
    setFilter:(f)=>{ currentFilter=f; drawFilters(); render() },
    setQuery:(q)=>{ query=(q||'').trim().toLocaleLowerCase('ru'); if(search) search.value=q||''; render() },
    render,
    getState:()=>({ current, currentFilter, query, categories, allItems })
  };
})();
